package com.kouta.design.resource

import androidx.compose.ui.graphics.Color

// Light Theme Color
val PrimaryLight = Color(0xFF7E4894)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFF8D8FF)
val OnPrimaryContainerLight = Color(0xFF320047)
val InversePrimaryLight = Color(0xFFEBB2FF)
val SecondaryLight = Color(0xFF69596D)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFF1DCF4)
val OnSecondaryContainerLight = Color(0xFF231728)
val TertiaryLight = Color(0xFF815250)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDAD8)
val OnTertiaryContainerLight = Color(0xFF331111)
val BackgroundLight = Color(0xFFFFFBFF)
val OnBackgroundLight = Color(0xFF1E1B1E)
val SurfaceLight = Color(0xFFFFFBFF)
val OnSurfaceLight = Color(0xFF1E1B1E)
val SurfaceVariantLight = Color(0xFFEBDFE9)
val OnSurfaceVariantLight = Color(0xFF4C444D)
val SurfaceTintLight = Color(0xFF7E4894)
val InverseSurfaceLight = Color(0xFF332F33)
val InverseOnSurfaceLight = Color(0xFFF6EFF3)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val OutlineLight = Color(0xFF7D747D)
val OutlineVariantLight = Color(0xFFCEC3CD)
val ScrimLight = Color(0xFF000000)

val ShadowLight = Color(0xFF000000)

// Dark Theme Color
val PrimaryDark = Color(0xFFEBB2FF)
val OnPrimaryDark = Color(0xFF4B1662)
val PrimaryContainerDark = Color(0xFF64307B)
val OnPrimaryContainerDark = Color(0xFFF8D8FF)
val InversePrimaryDark = Color(0xFF7E4894)
val SecondaryDark = Color(0xFFD4C0D7)
val OnSecondaryDark = Color(0xFF392C3D)
val SecondaryContainerDark = Color(0xFF504255)
val OnSecondaryContainerDark = Color(0xFFF1DCF4)
val TertiaryDark = Color(0xFFF5B7B5)
val OnTertiaryDark = Color(0xFF4C2524)
val TertiaryContainerDark = Color(0xFF663B39)
val OnTertiaryContainerDark = Color(0xFFFFDAD8)
val BackgroundDark = Color(0xFF1E1B1E)
val OnBackgroundDark = Color(0xFFE8E0E5)
val SurfaceDark = Color(0xFF1E1B1E)
val OnSurfaceDark = Color(0xFFE8E0E5)
val SurfaceVariantDark = Color(0xFF4C444D)
val OnSurfaceVariantDark = Color(0xFFCEC3CD)
val SurfaceTintDark = Color(0xFFEBB2FF)
val InverseSurfaceDark = Color(0xFFE8E0E5)
val InverseOnSurfaceDark = Color(0xFF1E1B1E)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val OutlineDark = Color(0xFF978E97)
val OutlineVariantDark = Color(0xFF4C444D)
val ScrimDark = Color(0xFF000000)

val ShadowDark = Color(0xFF000000)

// Common Color
